menu:
  #Archives: /archives
  # Blog: /favourite
  # Photos: /favorite
  Aboutme: /aboutme

description: 
social:
  weibo: 
  github: https://github.com/Wegnery219
  stack_overflow: 
  facebook: 
  twitter: 
  google_plus: 

page_comment: true
logo: /images/head2.jpeg
background:
  cover: /images/back.jpg
  color: cover-purple

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: 

google_analytics: UA-78918255-1
baidu_tongji: 9cdad07c755fa23f6aced510c6760e87
favicon: /images/small.png

image_stream:
  jquery: //cdn.bootcss.com/jquery/2.1.0/jquery.min.js
  jquery_lazyload: //cdn.bootcss.com/jquery.lazyload/1.9.1/jquery.lazyload.min.js
  img_placeholder: http://ww4.sinaimg.cn/large/e724cbefgw1etyppy7bgwg2001001017.gif
#disqus
disqus: 
  enable: true
  shortname:
  count: true

#mathjax
mathjax: true

# 'Read more' button
excerpt_link: 继续阅读

# Footer message
site_license: 本站点采用 <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>
theme_message: 基于 <a href="http://hexo.io">Hexo</a> 搭建，使用 <a href="https://github.com/monniya/hexo-theme-new-vno ">new-vno</a> 主题，由<a href="https://monniya.com ">@Monniya</a> 修改自 <a href="https://github.com/lenbo-ma/hexo-theme-vno" target="_blank">Vno</a>, 原创出自<a href="http://github.com/onevcat/vno" target="_blank">onevcat</a>
